config/routes.rb
Rails.application.routes.draw do
 

 

  get 'students/upload'

  get 'students/payment'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :students do
    collection { post :import }
    collection do
      post "pay"
    end
  end

end

app/models/student.rb
class Student < ActiveRecord::Base
	
	def self.import(file)
		begin
		  CSV.foreach(file.path, headers: true) do |row|
		    student = find_by_id(row["id"]) || new
		    student.attributes = row.to_hash.slice(*row.to_hash.keys)
		    student.date=nil
		    student.paid=0
		    student.save!
		  end
		rescue => e
	        # Rails.logger.error { "Encountered an error" }
      		"notok"
      	end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :authenticate_user!

  ####### System admin is 0
  ####### School admin is 1
  ####### School account is 2
  ####### Bank is 3
  def index
  	if current_user && current_user.user_type == 1 || current_user.user_type == 0
  		@students = Student.all
  	else
  		redirect_to authenticated_root_path, :alert => 'Access Denied!'
  	end
  end

  def show
  	if current_user && current_user.user_type == 1 || current_user.user_type == 0

  	else
  		redirect_to authenticated_root_path, :alert => 'Access Denied!'
  	end
  end

  def upload
  	if current_user && current_user.user_type == 2 || current_user.user_type == 0

  	else
  		redirect_to authenticated_root_path, :alert => 'Access Denied!'
  	end
  end

  def import
    if current_user && current_user.user_type == 2 || current_user.user_type == 0
  	  result = Student.import(params[:file])
      if result=="notok"
        redirect_to students_upload_path, :alert => "Error in file."
      else
  	    redirect_to students_upload_path, :notice => "Students imported."
      end
    else
      redirect_to authenticated_root_path, :alert => 'Access Denied!'
    end
  end

  def payment
  	if current_user && current_user.user_type == 3
      @students = Student.all
      @std = Student.new
  	else
  		redirect_to authenticated_root_path, :alert => 'Access Denied!'
  	end
  end

  def pay
    if current_user && current_user.user_type == 3
      @std = Student.find(params[:student][:id])
      # return render json: @std
      @std.paid = @std.paid.to_i + params[:student][:paid].to_i
      @std.date = params[:student][:date]
      @std.save!
      redirect_to students_payment_path, :success => 'Payment Updated!'
    else
      redirect_to authenticated_root_path, :alert => 'Access Denied!'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/home/index.html.erb
<script type="text/javascript">
  var d = document.getElementById("home");
d.className = d.className + " active";
</script>
<h1>Home</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scholastic</title>
  
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script src="//cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js"></script>
<script src="//cdn.datatables.net/plug-ins/9dcbecd42ad/integration/jqueryui/dataTables.jqueryui.js"></script>
<script src="//cdn.datatables.net/tabletools/2.2.0/js/dataTables.tableTools.min.js"></script>
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600" rel="stylesheet" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <link href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" rel="stylesheet" />
  <link href="//cdn.datatables.net/plug-ins/9dcbecd42ad/integration/jqueryui/dataTables.jqueryui.css" rel="stylesheet" />
  <link href="//cdn.datatables.net/tabletools/2.2.0/css/dataTables.tableTools.min.css" rel="stylesheet" />
 
  
</head>
<body style=" background-color:#eee">

<div class="navbar navbar-inverse navbar-fixed-top">
	
	<div class="navbar-inner">
		
		<div style="margin-left:100px;">
			
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<i class="icon-cog"></i>
			</a>
			<img src="<%= asset_path "img/logo/scs-logo.png"%>" style="width:80px; height:80px;" />
			
			<span style="font-size:28px; font-weight:bold">Scholastic</span>
			
			<% if current_user %>

				<ul class="nav pull-right" style="top:15px;">
					
					<!-- <li class="dropdown">
						<a href="<%#= edit_user_registration_path %>" class="dropdown-toggle" data-toggle="dropdown">
							<i class="icon-user"></i> 
							
						</a>
						
					</li> -->

					<li class="dropdown">
						<%= link_to edit_user_registration_path do %>
							<i class="icon-user"></i> <%= current_user.email%>
						<% end %>
						
					</li>

					<li class="dropdown">
						<%= link_to destroy_user_session_path, method: :delete do %>
							<i class="icon-off"></i> Logout
						<% end %>
						
					</li>
					
				</ul>
			<% end %>
			
			

		</div> <!-- /container -->
		
	</div> <!-- /navbar-inner -->
	
</div> <!-- /navbar -->


<% if current_user %>
<div class="subnavbar">

	<div class="subnavbar-inner">
	
		<div style="margin-left:100px;">

				<ul class="mainnav">
				
					<li class="" id="home"><!-- class->active -->
						<a href="<%= authenticated_root_path %>">
							<i class="icon-home"></i>
							<span>Home</span>
						</a>	    				
					</li>
					<% if current_user && current_user.user_type == 2  || current_user.user_type == 0 %>
					<li class="" id="csv">
						<a href="<%= students_upload_path %>">
							<i class="icon-plus"></i>
							<span>Upload a CSV File</span>
						</a>	    				
					</li>
					<%end%>
					
					<% if current_user && current_user.user_type == 1 || current_user.user_type == 0 %>
					<li class="" id="std">
						<a href="<%= students_path %>">
							<i class="icon-user"></i>
							<span>Students</span>
						</a>	    				
					</li>
					<% end %>
					
					
					<% if current_user && current_user.user_type == 3 %>
					<li class="" id="pay">
						<a href="<%= students_payment_path %>">
							<i class="icon-plus"></i>
							<span>Pay Fees</span>
						</a>	    				
					</li>
					<% end %>
					
				</ul>
		

		</div> <!-- /container -->
	
	</div> <!-- /subnavbar-inner -->

</div> <!-- /subnavbar -->
<% end %>

<div class="container" style="margin-top:30px;">
	<%= render partial: "partials/flash_message" %>
	<%= yield %>
</div>
<div style="margin:30px;"></div>



</body>
</html>

app/views/partials/_flash_message.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
  	<% name = name.to_s == 'success' ? 'success' : name.to_s %>
  	<% name = name.to_s == 'alert' ? 'danger' : name.to_s %>
	<% name = name.to_s == 'notice' ? 'info' : name.to_s %>    
    <div class="alert alert-<%= name %> main-alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg.html_safe, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/students/index.html.erb
<script type="text/javascript">
  var d = document.getElementById("std");
d.className = d.className + " active";
  $(document).ready(function() {
  

    $('#example').dataTable({
        dom: 'T<"clear">lfrtip',
        tableTools: {
            "sSwfPath": "//cdn.datatables.net/tabletools/2.1.5/swf/copy_csv_xls_pdf.swf",
            "aButtons": [
                {
                    "sExtends": "copy",
                    "sButtonText": "Copy to clipboard"
                },
                {
                    "sExtends": "csv",
                    "sButtonText": "Save to CSV"
                }
            ]

        }
    });
  });

</script>

<h2>Students</h2>
    <table id="example" class="display">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Branch</th>
          <th>Garde</th>
          <th>Amount</th>
          <th>Paid</th>
          <th>Remaining</th>
          <th>Date</th>
        </tr>
      </thead>
      <tbody>
        <% @students.try(:each) do |student| %>
          <tr>
            <td>
              <%= student.id %>
            </td>
            <td>
              <%= student.name %>
            </td>
            <td>
              <%= student.branch %>
            </td>
            <td>
              <%= student.grade %>
            </td>
            <td>
              <%= student.amount %>
            </td>
            <td>
              <%= student.paid %>
            </td>
            <td>
              <%= student.amount-student.paid %>
            </td>
            <td>
              <%= student.date %>
            </td>
            
          </tr>
        <% end %>
      </tbody>
    </table>

app/views/students/payment.html.erb
<script type="text/javascript">
  var d = document.getElementById("pay");
d.className = d.className + " active";

  $(document).ready(function() {
  

    $('#stdata').dataTable();
  });

</script>

<h2>Students</h2>
    <table id="stdata" class="display">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Branch</th>
          <th>Garde</th>
          <th>Amount</th>
          <th>Paid</th>
          <th>Remaining</th>
          <th>Date</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @students.try(:each) do |student| %>
          <tr>
            <td>
              <%= student.id %>
            </td>
            <td>
              <%= student.name %>
            </td>
            <td>
              <%= student.branch %>
            </td>
            <td>
              <%= student.grade %>
            </td>
            <td>
              <%= student.amount %>
            </td>
            <td>
              <%= student.paid %>
            </td>
            <td>
              <%= student.amount-student.paid %>
            </td>
            <td>
              <%= student.date %>
            </td>
            <td>
            	<div class="input-group" style="width:150px;">
			      <%= form_for @std ,:url => pay_students_path, method: :post do |f| %>
				      <%= f.number_field :paid, :class => 'form-control', :style => 'height:26px;width:100px;', :value => student.amount-student.paid,  in: 0..1000000 %>
				      <%= f.hidden_field :date, :value => DateTime.now %>
				      <%= f.hidden_field :id, :value => student.id %>
				      <!-- <input type="text" class="form-control" style="height:26px;"> -->
				      <span class="input-group-btn">
				        <button type="submit" class="btn btn-small btn-warning" type="button">Pay!</button>
				      </span>
				     <% end %>
			    </div><!-- /input-group -->
            </td>
            
          </tr>
        <% end %>
      </tbody>
    </table>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>

app/views/students/upload.html.erb
<script type="text/javascript">
  var d = document.getElementById("csv");
d.className = d.className + " active";
</script>
<h4>Upload Students List via <span style="font-style:italic;">CSV</span> File</h4>
<u><strong>First row should be : id, name, branch, grade, amount </strong></u>


<%= form_tag import_students_path, multipart: true do %>
  <%= file_field_tag :file, :accept => 'text/csv' %>
  <%= submit_tag "Import", :class => 'btn' %>
<% end %>